paths:
  /api/project/total:
    get:
      summary: 전체 프로젝트 조회
      description: 프로젝트의 모든 정보를 가져옵니다.
      parameters:
        - name: page
          description: "1~8 (1: default) / Up to 8 pages per page."
          in: query
          schema:
            type: Number
        - name: sort
          description: "1: 이름순, 2: 인기순 (1: default)"
          in: query
          schema:
            type: Number
      responses:
        '200':
          description: 프로젝트 조회 성공
  /api/insert/image:
    post:
      summary: 이미지 추가
      description: s3에 이미지를 저장합니다.
      
      responses:
        '200':
          description: 이미지 업로드 성공
  
  /api/project/{projectId}/addLike:
    post:
      summary: 좋아요 추가
      description: params로 project의 ID를 가져와서 그 프로젝트의 좋아요를 추가합니다. 
      parameters:
        - name: projectId
          description: 프로젝트의 id
          in: path
          schema:
            type: String
          examples:
            Sample:
              value: "632aeb2752930aa3ed38a101"
              summary: "example project Id"
      responses:
        '200':
          description: 좋아요 추가 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
  
